Repository weareopensource/Node, pull requests merged in 2021-03, with the labels that each got.

#1238 feat(all): Add swagger support
  .gitignore
  config/assets.js
  config/defaults/development.js
  config/index.js
  lib/services/express.js
  modules/core/doc/index.yml
  modules/home/doc/components.yml
  modules/home/doc/home.yml
  package-lock.json
  package.json
  public/.gitkeep
Labels: Feat

#1259 refactor(services): mongoose await async ♻️
  config/defaults/development.js
  lib/services/mongoose.js
Labels: Effort easy (h), Refactor

#1260 refactor(users, tasks): refactor id add like ts ♻️
  modules/tasks/controllers/tasks.controller.js
  modules/users/controllers/admin.controller.js
  modules/users/controllers/users.data.controller.js
  modules/users/controllers/users/users.profile.controller.js
  modules/users/tests/user.crud.tests.js
Labels: Effort easy (h), Refactor

#1261 docs(readme): fix docker instructions 📝
  README.md
Labels: Docs, Effort easy (h)

#1268 feat(services): add bodyparser config to express ✨
  config/defaults/development.js
  lib/services/express.js
Labels: Effort easy (h), Feat

#1284 Feat uprgrade lint
  .drone.yml
  .eslintrc.js
  .prettierrc.js
  .travis.yml
  config/assets.js
  config/defaults/development.js
  config/index.js
  gulpfile.js
  jest.config.js
  lib/app.js
  lib/helpers/files.js
  lib/helpers/joi.js
  lib/helpers/responses.js
  lib/middlewares/model.js
  lib/middlewares/policy.js
  lib/services/express.js
  lib/services/logger.js
  lib/services/mongoose.js
  lib/services/multer.js
  lib/services/seed.js
  modules/auth/config/strategies/apple.js
  modules/auth/config/strategies/google.js
  modules/auth/config/strategies/local.js
  modules/auth/controllers/auth.controller.js
  modules/auth/controllers/auth/auth.authentication.controller.js
  modules/auth/controllers/auth/auth.password.controller.js
  modules/auth/services/auth.service.js
  modules/core/tests/core.lib.tests.js
  modules/home/policies/home.policy.js
  modules/home/routes/home.route.js
  modules/home/services/home.service.js
  modules/home/tests/home.crud.tests.js
  modules/tasks/models/tasks.model.mongoose.js
  modules/tasks/policies/tasks.policy.js
  modules/tasks/repositories/tasks.repository.js
  modules/tasks/routes/tasks.routes.js
  modules/tasks/tests/tasks.crud.tests.js
  modules/uploads/models/uploads.model.mongoose.js
  modules/uploads/policies/uploads.policy.js
  modules/uploads/repositories/uploads.repository.js
  modules/uploads/routes/uploads.routes.js
  modules/uploads/tests/uploads.crud.tests.js
  modules/users/controllers/users.controller.js
  modules/users/models/user.model.mongoose.js
  modules/users/models/user.schema.js
  modules/users/policies/users.policy.js
  modules/users/repositories/user.repository.js
  modules/users/routes/admin.routes.js
  modules/users/routes/users.routes.js
  modules/users/tests/user.crud.tests.js
  modules/users/tests/user.schema.tests.js
  package-lock.json
  package.json
  scripts/treatments/reset-password.js
  scripts/treatments/upgrade-users-sparse-index.js
  server.js
Labels: Build, Effort easy (h)

#1285 build(lint): adjust length rule 🏗
  .prettierrc.js
  config/defaults/development.js
  config/defaults/production.js
  lib/app.js
  lib/middlewares/model.js
  lib/services/seed.js
  modules/auth/config/strategies/apple.js
  modules/auth/config/strategies/google.js
  modules/auth/controllers/auth/auth.password.controller.js
  modules/uploads/controllers/uploads.controller.js
  modules/users/repositories/user.repository.js
  modules/users/routes/users.routes.js
  modules/users/tests/user.schema.tests.js
Labels: Build, Effort easy (h)

#1286 build(lint): remove useless override 🏗
  .eslintrc.js
Labels: Build
